# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('age', models.DateTimeField()),
                ('bio', models.CharField(max_length=255)),
                ('link1', models.URLField()),
                ('link2', models.URLField()),
                ('location', models.CharField(max_length=150)),
                ('pic', models.FileField(null=True, upload_to='')),
                ('banner', models.FileField(null=True, upload_to='')),
                ('strikes', models.IntegerField(default=0)),
                ('suspended', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
