# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180427_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link1',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link2',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
