# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180430_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='sent',
            field=models.BooleanField(default=True),
        ),
    ]
