# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
