# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
