# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
        migrations.DeleteModel(
            name='PayoutInfo',
        ),
    ]
